### ISSUE TITLE
Error message when trying to run ReadDevicetoCloudMessages.js

### ISSUE THREAD

**Issue by rukmani-msft** [Azure-Samples/azure-iot-samples-node#23]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Follow the tutorial in https://docs.microsoft.com/en-us/azure/iot-hub/quickstart-send-telemetry-node
When trying to run ReadDevicetoCloudMessages.js, the following exception is thrown. 
I can monitor the messages in DeviceExplorer in VS Code.

### Any log messages given by the failure
>internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module '@azure/event-hubs'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/rukmanigopalan/Downloads/azure-iot-samples-node-master/iot-hub/Quickstarts/read-d2c-messages/ReadDeviceToCloudMessages.js:23:41)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by rukmani-msft** [comment]
FYI - as indicated in the tutorial , the zip file in the archive was used.

**Comment by yzhong94** [comment]
@rukmani-msft were you able to run the sample after npm install?

**Comment by anthonyvercolano** [comment]
No activity.
